### ISSUE TITLE
Is this project abandonned ?

### ISSUE THREAD

**Issue by Thedarklife74** [Xonshiz/anime-dl#117]
Hi,
the project is abandonned ? It's not working since more than a month now. Impossible to login throught the script

thanks

**Comment by Fantosism** [comment]
I'm using it currently. There are a few fixes in comments for other issues.

**Comment by Kanekid2m** [comment]
It did not work for me. I downl,oaded the fixed version that @EpicUnknown posted and still did not work. I also edited the crunchyroll.py with bDub and also did not work. Installed Python 3.7 instead of 3.8 also did not work and keep getting this error.

$ python __main__.py -u ----- -p ---- -i https://www.crunchyroll.com/black-clover
Trying to login...
Let me check again...
Unable to Log you in. Check credentials again.
Failed Login!!!

**Comment by Fantosism** [comment]
I'm using master with no edits to the code base. The compiled version is out of date. If you're getting an invalid credentials error, you probably have invalid credentials or you're using a symbol that doesn't seem to want to convert well.  Try changing your Crunchyroll pass to something with only alphanumerics. Verify that you can login with the new pass and see if the error persists on anime-dl. I ran this last night actually on that exact same link:  
  
```bash  
$ python ./__main__.py -i "https://www.crunchyroll.com/black-clover" -u "XXX@XXX.com" -p "XXX" -r "1080" -rn 26-100  
```
  
```
python --version
// Python 3.8.2  
```  
  
What does your error log say when you run the command with --verbose?

**Comment by 3bood-kr** [comment]
does it work with funimation?

**Comment by Zebraslive** [comment]
https://github.com/Zebraslive/Mass-Anime-Downloader

**Comment by Xonshiz** [comment]
It's not abandoned. But, I have to re-write this code to tune up things. I'm currently working on other smaller scripts and fixing those issues first and then I'll slowly come to this project. If you pull the code and run it, I think it'll work still. Initial setup for code could be a drag.

For any new comer here, looking for any updates, Zeraslive has linked his application here. I am not going to delete their comment, but, I cannot guarantee that tool. Do check the code before accessing anything. Since it's out in open, I don't think it'll do any harm. But, please be cautious of any script/tool you come across. This also applies for any of the things I've posted here (comic-dl, anime-dl, hulu subs downloader etc.)
