### ISSUE TITLE
Error 2 System couldn't found the specified file

### ISSUE THREAD

**Issue by GNBRKR** [Xonshiz/anime-dl#23]
Hi, my problem is when run, this message appears:
```
C:\cr> anime-dl.exe -i http://www.crunchyroll.com/hundred/ -u USER -p PASS -v
Trying to login...
Logged in successfully...
Total Episodes to download : 12
Downloading Hundred - 1 [1280x720].enUS.ass ...
Couldn't connect to the m3u8 file download link...
[Error 2] System couldn't found the specified file
```
Any idea? Thanks...

**Comment by Xonshiz** [comment]
Please check the readme and post the "verbose" dump as well.

**Comment by Xonshiz** [comment]
Update : Just ran the script on my end and It's working just fine. Please make sure that you have to updated .exe file and your internet is working fine. And dump the verbose log if you still want me to take a look at the issue. Since you haven't posted any verbose log and the script worked just fine on my end, I'm closing this issue. If you still face the issue, please comment here with everything and I'll check.
