### ISSUE TITLE
Feature(s) Request

### ISSUE THREAD

**Issue by Haejien** [Xonshiz/anime-dl#3]
Here's a few features that would be extremely useful down the road:

- Download entire series from show link (www.crunchyroll.com/seriesname)
> _I assume this one was already planned, but just to have it down on paper_
> _Also with this it would be cool to be able to set a flag that would allow you to download more than one episode at once, however I don't know how crunchyroll handles multiple threads so maybe this isn't feasible_

- Merge subtitles and video file into mkv
>_Maybe even take it a step further and properly set the language for each file in the mkv container_

- Cache site login details/token
> _Once again I'm not too sure how the token works so if it expires then this probably wouldn't work._

**Comment by Xonshiz** [comment]
Hey,

* Whole series downloading is supported in this tool. But, that version is available on my [patreon only](https://www.patreon.com/xonshiz) (for a week or so). After a week or so, I'll port that functionality here. I didn't understand this part
```
Also with this it would be cool to be able to set a flag that would allow you to download more than one episode at once
```

Do you mean that you want the script to download episodes simultaneously? If yes, I think that it'll be a bad idea. Because videos are a big thing to download/upload. Suppose there's an anime like One Piece or Fairy Tail or Naruto Shippuuden, they have like 500+ episodes. If every episode is downloaded simultaneously, it'll cause bottleneck problems. And even your system might crash.

* I can do this, not a problem. I actually have a version on my end that can do this. However, it requires one more dependency... mkvmerge. I don't want to add one more external binary dependecy. I'm actually trying to get rid of ffmpeg as well, tbh. I'll implement this at a later stage.

* Yes, that is planned. To make a config file or something so that you won't have to pass the credentials every time. I'll implement this is near future. I don't want to save or take cache or anything because its CloudFlare and they will definitely change something in this sooner or later and it might break the script. So, I'll be taking credentials from a config file.

# Things I will push in new update : 

* Support for Funimation. Since Funimation changed their website, I was looking for ways to download from Funimation and found [this on Youtube-dl](https://github.com/rg3/youtube-dl/issues/11773#issuecomment-273772282). But, after inspecting their new website inside out, I figured out a faster and a better way. I have yet to implement this one.

**Comment by Haejien** [comment]
I was referring to setting something like a "transfers" (e.g. --transfers=10) flag. I know you couldn't download 400 episodes at once but having gigabit internet I could easily handle 5+ concurrent streams. As for dependencies, it is sort of a pain to use them on windows, however on linux, which what I feel most people would be using anyway, it's pretty easy to manage.

**Comment by Xonshiz** [comment]
I don't think mkvmerge and FFmpeg come pre-installed or maintained on Linux as well (will check later today on my machine). I see the transfer flag thing now. Nice idea. I'll implement it after I make add support for Funimation :)

**Comment by Haejien** [comment]
Well (referring to ubuntu), in the case of mkvmerge you do have to add a repository source, but ffmpeg was removed in in 14.xx but re added into the default repository starting in 15.04.

**Comment by Xonshiz** [comment]
Ah, I see. But, I'm trying to make this script run on every platform without any external binary. dependency. I'll see what I can do :+1:

**Comment by MrDonGato** [comment]
any way to download only subtitles? i try to download only the subs and use other sources for video.

**Comment by Xonshiz** [comment]
Nothing for just subs yet.

**Comment by MrDonGato** [comment]
i'll subscribe to this to see when you put subs-only :D

**Comment by BTSpaniel** [comment]
Subs only and mkv merge (windows only because i program in batch, because i can.)

https://www.reddit.com/r/megalinks/comments/5xm4b8/meta_croll_batch_dloader_and_converter/

**Comment by Xonshiz** [comment]
Whole show ripping support added. Only subs part should come by next week, I guess.

**Comment by Xonshiz** [comment]
Added the "Only Subs" download part. Will be closing this.
