### ISSUE TITLE
Funimation: Under Development!

### ISSUE THREAD

**Issue by leptoid** [Xonshiz/anime-dl#8]
Hello.  I tested out your script today on Funimation as a registered user.  I dislike having buffering issues while watching content I paid to stream on there, thus I thought this would be a good idea... D/L, then watch.
Here is the result:
```
D:\anime-dl-master\anime_dl>__main__.py -i "https://www.funimation.com/shows/tokyo-ghoul/va-new-surge/uncut/" -u myusername -p mypassword -l english -r 720p
Under development!

D:\anime-dl-master\anime_dl>
```
Any thoughts on the "Under development!" section?  It only posts when I insert a username/password.  On the other hand, I can't get my content without it.  Obviously, I assume it is just something you're working on and also that patience is a virtue.

Once I find something to watch that I won't run into the Username/Pass issue, I'm looking forward to using this.  Thanks for the program!

**Comment by Xonshiz** [comment]
Hello!
As mentioned in the script, this section is under development. I actually have a version ready for this on my end, but it has some issue which I'm unable to fix. I do this in my free time and I haven't been able to take anything major for past few weeks and it would stat same for next 2 months.

I'll see if I can get some time today and add Funimation here in a day or so. But, it'll be with some problems, even if it works.

**Comment by leptoid** [comment]
No problem.  I've done some programming in the past, so I understand the amount of work that goes into projects.  When you get around to it I appreciate it.  No rush on my part though.  At least it is working as designed. :)

**Comment by mbivol10** [comment]
Ok I am currently working on more less getting this to work. I am willing to get premium but the problem is they changed structure quite a bit ... The token became harder to generate and everything is much more encrypted ... I'd love to help .. I got them downloading just fine but I want to automate this process and it is a lot more work in programming to do .... Hows the progress on your end?

**Comment by Xonshiz** [comment]
I've written something and it's supposed to download Dubbed and Subbed video. But, it's just downloading the Subbed videos. I figured how to generate that 8 digit token and stuff, wasn't that big of a deal. I'll push my version next month. So, at least the subbed videos can be downloaded. Honestly, the structure change is both, great and sucky. Great because now they're using APIs, which made it easier for other programmers to mess around. Sucky because it's a little hard to get it working.

**Comment by Xonshiz** [comment]
If you could contact me at xonshiz[at]psychoticelites.com, we can see each other's process of ripping from Funimation. Might help us with something.

**Comment by Xonshiz** [comment]
I have implemented the Funimation support. But, it can only download the subbed episodes as of now. Test it and let me know. :)
