### ISSUE TITLE
Blocked IP, what to do?

### ISSUE THREAD

**Issue by giggioman00** [Xonshiz/anime-dl#89]
As above. the script workd fine now from PC but, if I try to use in on my server, I get the 403 forbidden error. I read they have blocked every request from datacenters' IP. This make me think that hiding my server under proxy is useless, becuase those are often from datacenters' IP. Do you have any idea how I can turn around this problem?

**Comment by Abu3safeer** [comment]
You already know that the only way is to use a different IP, I have a server that is not blocked, so they does not cover all IPs.

**Comment by axipher** [comment]
Is your server located in some datacenter?  I only have linux based headless servers running in datacenters so can't easily test anime-dl on something other than my own personal IP.  I've been running a script daily at 1PM EST that checks 20-30 shows each time for new episodes and I have yet to be blocked.  I'm not guaranteeing that your personal IP won't eventually get blocked, but I've been doing it this way for 6 months with my public IP rotating once every few weeks either by my ISP, or me restarting it because of a firmware update.

As for solving your problem in it's current form, all I can really recommend is using a VPN on your server that comes out at a public IP that isn't blocked by Crunchyroll.

I'm also assuming you are using Crunchyroll as you didn't specify what site you are downloading from.

**Comment by giggioman00** [comment]
> 
> 
> You already know that the only way is to use a different IP, I have a server that is not blocked, so they does not cover all IPs.

That's useful, thank you



> 
> 
> Is your server located in some datacenter? I only have linux based headless servers running in datacenters so can't easily test anime-dl on something other than my own personal IP. I've been running a script daily at 1PM EST that checks 20-30 shows each time for new episodes and I have yet to be blocked. I'm not guaranteeing that your personal IP won't eventually get blocked, but I've been doing it this way for 6 months with my public IP rotating once every few weeks either by my ISP, or me restarting it because of a firmware update.
> 
> As for solving your problem in it's current form, all I can really recommend is using a VPN on your server that comes out at a public IP that isn't blocked by Crunchyroll.
> 
> I'm also assuming you are using Crunchyroll as you didn't specify what site you are downloading from.

yes it's CR

**Comment by Nicnl** [comment]
Let's assume that sending kind mail to Crunchyroll and ask them to unblock your IP won't work.  

Here are all your options without any personal opinions:

- You can change your server and get an unblocked IP
  => Well, do it
- You can find and install a VPN with an unblocked IP
  => Well, do it
- You won't/can't change your server or get an unblocked IP and cannot get another one that's not blocked.
  => Sorry, I'm agraid you're going to have to live with it

**Comment by Xonshiz** [comment]
This issue is not related to anime-dl. @Nicnl has pointed out the methods I would have suggested. Please try those.

Thanks @Nicnl for helping out :)
