### ISSUE TITLE
add the ability to select a collection instead of all of them (useful to ignore dubs)

### ISSUE THREAD

**Issue by Abu3safeer** [Xonshiz/anime-dl#95]
Hello everyone, 

I have checked [simplymemes/crunchyroll-dl](https://github.com/simplymemes/crunchyroll-dl), and it is awesome for hardsub, too bad it does not support softsub until now.

but I found a great idea on [simplymemes/crunchyroll-dl](https://github.com/simplymemes/crunchyroll-dl), it is selecting specific collection.

Normally it would download all of these collections, but I only need the japanese version, not dubbed.
![image](https://user-images.githubusercontent.com/12091003/55623412-99086880-57ab-11e9-9e88-d832cae8d2be.png)

so is it possible to select specific collection?

For now I am using "Q" button to  to stop download every dubbed episode, but it is not really effective way.

any ideas?

**Comment by axipher** [comment]
I believe the purpose of this project was to provide a simple way to bulk download a show for offline viewing so added features like that are slow as there are only a couple people contributing to the codebase here.

It's annoying, but you could try using the -range option to only download the ranges of episodes you want that would fall under different collections.

What I do is just leave the DUB's in the Output folder so that they get skipped each time I download new episodes.  I know not everyone can afford cheap storage, so that isn't a good blanket solution by any means.

I've been meaning to take a crack at the code to implement a archive text file similar to youtube-dl, but just haven't had the time or energy for it yet.

**Comment by Abu3safeer** [comment]
You are correct about the space, specially that every hard disk consumes more power.

anyway I just liked the idea, I am not a Python programmer so I really can't too much, just edit some basic codes from my programming knowledge.

**Comment by axipher** [comment]
A line of code could possibly be added to ignore any episode with " dub " in them, but that would be a pretty low effort solution.

An alternative would be adding some input flag that you can feed a string like below that would required any word with a "+" before it to appear in the episode and skip any episodes that have any words with a "-" before them
`.\anime-dl.exe -v -i <show_name> -u username -p password -r 1080p -textqualifier "-dub -PV -OVA +Episode"`
or
`.\anime-dl.exe -v -i <show_name> -u username -p password -r 1080p -tq "-dub -PV -OVA +Episode"`
The above code would skip any episodes where the filename contains PV, dub or OVA in the title and only download episodes that have "Episode" in the filename.

Would probably have to take more time inspecting the playlist file to see if it has enough details that you can easily group episodes by collections like Crunchyroll does already.
